/**
 * The goal ideas offered on the landing page, in reveal order.
 *
 * Each suggestion carries its own `theme`, which is what drives the emojis
 * shown when it is hovered or picked. That used to be a separate 150-entry
 * emoji -> theme map, which could only hold one theme per emoji: the 23
 * emojis used by more than one suggestion all had to share a single theme
 * (🧊 "Learn to make cocktails" inherited `ice` from "Learn ice sculpting"),
 * and the two suggestions whose emoji was missing from the map fell back to
 * random emojis. A theme per suggestion, checked by the compiler, removes
 * both failure modes.
 */

import type { ThemeKey } from "./themes";

export type Suggestion = {
  emoji: string;
  text: string;
  theme: ThemeKey;
};

export const SUGGESTIONS: readonly Suggestion[] = [
  // --- initial 8 ---
  { emoji: "🎣", text: "Learn to fly fish", theme: "water" },
  { emoji: "🏃", text: "Run a marathon", theme: "run" },
  { emoji: "🎸", text: "Learn to play guitar", theme: "music" },
  { emoji: "💼", text: "Start a small business", theme: "biz" },
  { emoji: "🐱", text: "Raise a kitten", theme: "animal" },
  { emoji: "🥌", text: "Learn curling", theme: "ice" },
  { emoji: "🕯️", text: "Make a candle", theme: "art" },
  // --- batch 2 (8 more → 16) ---
  { emoji: "📖", text: "Write a novel", theme: "write" },
  { emoji: "🤿", text: "Get scuba certified", theme: "water" },
  { emoji: "🍺", text: "Brew my own beer", theme: "drink" },
  { emoji: "🏄", text: "Learn to surf", theme: "water" },
  { emoji: "📱", text: "Build a mobile app", theme: "tech" },
  { emoji: "🥬", text: "Grow a vegetable garden", theme: "garden" },
  { emoji: "🧘", text: "Become a yoga instructor", theme: "zen" },
  { emoji: "🍄", text: "Become a mushroom forager", theme: "garden" },
  // --- batch 3 (16 more → 32) ---
  { emoji: "🚗", text: "Restore a vintage car", theme: "ride" },
  { emoji: "⛵", text: "Learn to sail", theme: "water" },
  { emoji: "🎙️", text: "Start a podcast", theme: "write" },
  { emoji: "🐝", text: "Become a beekeeper", theme: "garden" },
  { emoji: "♟️", text: "Master chess", theme: "game" },
  { emoji: "🏺", text: "Learn pottery", theme: "art" },
  { emoji: "🏅", text: "Train for an Ironman", theme: "run" },
  { emoji: "🏠", text: "Build a cabin", theme: "build" },
  { emoji: "🤟", text: "Learn sign language", theme: "lang" },
  { emoji: "🍷", text: "Become a sommelier", theme: "drink" },
  { emoji: "🎥", text: "Start a YouTube channel", theme: "write" },
  { emoji: "⚒️", text: "Learn blacksmithing", theme: "build" },
  { emoji: "✈️", text: "Get a pilot's license", theme: "advent" },
  { emoji: "🎨", text: "Master watercolor painting", theme: "art" },
  { emoji: "🛸", text: "Build a drone", theme: "tech" },
  { emoji: "🧗", text: "Learn to rock climb", theme: "advent" },
  // --- the full glorious list ---
  { emoji: "📸", text: "Become a wildlife photographer", theme: "advent" },
  { emoji: "🔥", text: "Learn to weld", theme: "build" },
  { emoji: "🚚", text: "Start a food truck", theme: "biz" },
  { emoji: "🎬", text: "Write a screenplay", theme: "write" },
  { emoji: "🥊", text: "Learn kickboxing", theme: "combat" },
  { emoji: "🌳", text: "Build a treehouse", theme: "build" },
  { emoji: "🍞", text: "Master sourdough baking", theme: "bake" },
  { emoji: "🎧", text: "Learn to DJ", theme: "music" },
  { emoji: "❤️", text: "Start a nonprofit", theme: "biz" },
  { emoji: "🤺", text: "Learn fencing", theme: "combat" },
  { emoji: "🔭", text: "Build a telescope", theme: "science" },
  { emoji: "🛹", text: "Learn to skateboard", theme: "ride" },
  { emoji: "🦋", text: "Start a butterfly garden", theme: "garden" },
  { emoji: "📐", text: "Master origami", theme: "art" },
  { emoji: "🌌", text: "Learn astrophotography", theme: "science" },
  { emoji: "🤖", text: "Build an Arduino robot", theme: "tech" },
  { emoji: "⛷️", text: "Learn to ski", theme: "ice" },
  { emoji: "📚", text: "Start a book club", theme: "write" },
  { emoji: "☕", text: "Master espresso making", theme: "drink" },
  { emoji: "🏹", text: "Learn archery", theme: "combat" },
  { emoji: "🏎️", text: "Build a go-kart", theme: "ride" },
  { emoji: "🥃", text: "Become a whiskey connoisseur", theme: "drink" },
  { emoji: "🪵", text: "Learn woodworking", theme: "build" },
  { emoji: "✍️", text: "Start a blog", theme: "write" },
  { emoji: "🫧", text: "Learn glassblowing", theme: "art" },
  { emoji: "🖨️", text: "Build a 3D printer", theme: "tech" },
  { emoji: "🥖", text: "Master bread baking", theme: "bake" },
  { emoji: "🤸", text: "Learn parkour", theme: "run" },
  { emoji: "🌻", text: "Start a community garden", theme: "garden" },
  { emoji: "🐠", text: "Become a certified diver", theme: "water" },
  { emoji: "💎", text: "Learn lapidary", theme: "art" },
  { emoji: "⚙️", text: "Build a CNC machine", theme: "build" },
  { emoji: "🍄", text: "Learn to forage", theme: "garden" },
  { emoji: "🧺", text: "Start a farmers market stand", theme: "biz" },
  { emoji: "🪢", text: "Master macramé", theme: "art" },
  { emoji: "🏍️", text: "Learn to ride a motorcycle", theme: "ride" },
  { emoji: "🎹", text: "Build a synthesizer", theme: "music" },
  { emoji: "🏔️", text: "Become a mountain guide", theme: "advent" },
  { emoji: "🧳", text: "Learn leatherworking", theme: "art" },
  { emoji: "👕", text: "Start a clothing brand", theme: "biz" },
  { emoji: "🍣", text: "Master sushi making", theme: "cook" },
  { emoji: "🪂", text: "Learn to paraglide", theme: "advent" },
  { emoji: "🏡", text: "Build a tiny house", theme: "build" },
  { emoji: "✒️", text: "Learn calligraphy", theme: "art" },
  { emoji: "🖼️", text: "Learn screen printing", theme: "art" },
  { emoji: "🕯️", text: "Start a candle business", theme: "biz" },
  { emoji: "🍜", text: "Master Thai cooking", theme: "cook" },
  { emoji: "🏂", text: "Learn to snowboard", theme: "ice" },
  { emoji: "🛶", text: "Build a kayak", theme: "build" },
  { emoji: "🏞️", text: "Become a trail runner", theme: "run" },
  { emoji: "📕", text: "Learn bookbinding", theme: "art" },
  { emoji: "🧀", text: "Start a cheese-making hobby", theme: "cook" },
  { emoji: "☕", text: "Master latte art", theme: "drink" },
  { emoji: "🛼", text: "Learn to inline skate", theme: "ride" },
  { emoji: "📻", text: "Become a ham radio operator", theme: "tech" },
  { emoji: "💃", text: "Learn to tap dance", theme: "perform" },
  { emoji: "🪴", text: "Start a terrarium business", theme: "garden" },
  { emoji: "🍛", text: "Master Indian cooking", theme: "cook" },
  { emoji: "🌊", text: "Learn to windsurf", theme: "water" },
  { emoji: "🍕", text: "Build a pizza oven", theme: "build" },
  { emoji: "🏋️", text: "Become a CrossFit athlete", theme: "run" },
  { emoji: "🧺", text: "Learn basket weaving", theme: "art" },
  { emoji: "🫖", text: "Start a kombucha brewery", theme: "drink" },
  { emoji: "🥐", text: "Master French pastry", theme: "bake" },
  { emoji: "🐴", text: "Learn horseback riding", theme: "animal" },
  { emoji: "🔥", text: "Build a fire pit", theme: "build" },
  { emoji: "🐦", text: "Become a bird watcher", theme: "animal" },
  { emoji: "🤹", text: "Learn to juggle", theme: "perform" },
  { emoji: "🌶️", text: "Start a hot sauce brand", theme: "biz" },
  { emoji: "🥟", text: "Master dumpling making", theme: "cook" },
  { emoji: "⛸️", text: "Learn ice skating", theme: "ice" },
  { emoji: "🥩", text: "Build a smokehouse", theme: "build" },
  { emoji: "🎤", text: "Become a standup comedian", theme: "perform" },
  { emoji: "🧶", text: "Learn to knit", theme: "art" },
  { emoji: "🧼", text: "Start a soap business", theme: "biz" },
  { emoji: "🍜", text: "Master ramen from scratch", theme: "cook" },
  { emoji: "🛶", text: "Learn to paddleboard", theme: "water" },
  { emoji: "🚤", text: "Build a boat", theme: "build" },
  { emoji: "🏊", text: "Become a marathon swimmer", theme: "water" },
  { emoji: "🧵", text: "Learn embroidery", theme: "art" },
  { emoji: "💍", text: "Start a jewelry line", theme: "biz" },
  { emoji: "🍖", text: "Master BBQ smoking", theme: "cook" },
  { emoji: "🏄", text: "Learn to wakeboard", theme: "water" },
  { emoji: "🌿", text: "Build a greenhouse", theme: "garden" },
  { emoji: "🎙️", text: "Become a voice actor", theme: "perform" },
  { emoji: "🧶", text: "Learn to crochet", theme: "art" },
  { emoji: "🪴", text: "Start a plant nursery", theme: "garden" },
  { emoji: "🫙", text: "Master fermentation", theme: "cook" },
  { emoji: "🪁", text: "Learn to kitesurf", theme: "water" },
  { emoji: "🧖", text: "Build a sauna", theme: "build" },
  { emoji: "🧠", text: "Become a trivia host", theme: "game" },
  { emoji: "🔪", text: "Learn whittling", theme: "build" },
  { emoji: "🛍️", text: "Start a vintage shop", theme: "biz" },
  { emoji: "🍫", text: "Master chocolate making", theme: "cook" },
  { emoji: "🦇", text: "Learn to spelunk", theme: "advent" },
  { emoji: "🧗", text: "Build a climbing wall", theme: "build" },
  { emoji: "🐕", text: "Become a dog trainer", theme: "animal" },
  { emoji: "🏺", text: "Learn to throw pottery on a wheel", theme: "art" },
  { emoji: "💐", text: "Start a flower farm", theme: "garden" },
  { emoji: "🍝", text: "Master pasta from scratch", theme: "cook" },
  { emoji: "🚵", text: "Learn to mountain bike", theme: "ride" },
  { emoji: "🎛️", text: "Build a recording studio", theme: "music" },
  { emoji: "📜", text: "Become a local historian", theme: "write" },
  { emoji: "🧵", text: "Learn to spin yarn", theme: "art" },
  { emoji: "📷", text: "Start a photography business", theme: "biz" },
  { emoji: "🥟", text: "Master dim sum", theme: "cook" },
  { emoji: "⛸️", text: "Learn figure skating", theme: "ice" },
  { emoji: "🛹", text: "Build a skatepark", theme: "build" },
  { emoji: "🏕️", text: "Become a scoutmaster", theme: "advent" },
  { emoji: "🪟", text: "Learn to make stained glass", theme: "art" },
  { emoji: "🧁", text: "Start a bakery", theme: "bake" },
  { emoji: "🎭", text: "Learn improv comedy", theme: "perform" },
  { emoji: "🦜", text: "Raise backyard chickens", theme: "farm" },
  { emoji: "🧊", text: "Learn ice sculpting", theme: "ice" },
  { emoji: "🎪", text: "Learn aerial silks", theme: "perform" },
  { emoji: "🌾", text: "Start a homestead", theme: "farm" },
  { emoji: "🧬", text: "Learn bioinformatics", theme: "tech" },
  { emoji: "🏰", text: "Build a medieval forge", theme: "build" },
  { emoji: "🎯", text: "Master darts", theme: "game" },
  { emoji: "🧲", text: "Build an electromagnet", theme: "science" },
  { emoji: "🦷", text: "Learn dental carving", theme: "art" },
  { emoji: "🪨", text: "Build a rock garden", theme: "garden" },
  { emoji: "🌶️", text: "Grow the hottest pepper", theme: "garden" },
  { emoji: "🎲", text: "Design a board game", theme: "game" },
  { emoji: "🧪", text: "Learn home chemistry", theme: "science" },
  { emoji: "🏺", text: "Make my own ceramics", theme: "art" },
  { emoji: "🧊", text: "Learn to make cocktails", theme: "drink" },
  { emoji: "🎻", text: "Learn the violin", theme: "music" },
  { emoji: "🪕", text: "Learn the banjo", theme: "music" },
  { emoji: "🥁", text: "Learn the drums", theme: "music" },
  { emoji: "🎷", text: "Learn the saxophone", theme: "music" },
  { emoji: "🎺", text: "Learn the trumpet", theme: "music" },
  { emoji: "🪈", text: "Learn the flute", theme: "music" },
  { emoji: "🪗", text: "Learn the accordion", theme: "music" },
  { emoji: "📝", text: "Write poetry", theme: "write" },
  { emoji: "🎮", text: "Make an indie video game", theme: "tech" },
  { emoji: "🖥️", text: "Build a PC from scratch", theme: "tech" },
  { emoji: "🔐", text: "Learn cybersecurity", theme: "tech" },
  { emoji: "📊", text: "Master data visualization", theme: "tech" },
  { emoji: "🌐", text: "Learn a new language", theme: "lang" },
  { emoji: "🇯🇵", text: "Learn Japanese", theme: "lang" },
  { emoji: "🇫🇷", text: "Learn French", theme: "lang" },
  { emoji: "🇰🇷", text: "Learn Korean", theme: "lang" },
  { emoji: "🇧🇷", text: "Learn Portuguese", theme: "lang" },
  { emoji: "🇸🇦", text: "Learn Arabic", theme: "lang" },
  { emoji: "🇨🇳", text: "Learn Mandarin", theme: "lang" },
  { emoji: "🧮", text: "Learn to speed-solve Rubik's cubes", theme: "game" },
  { emoji: "🪄", text: "Learn magic tricks", theme: "perform" },
  { emoji: "🎭", text: "Join a theater troupe", theme: "perform" },
  { emoji: "💪", text: "Get a pull-up to handstand", theme: "run" },
  { emoji: "🧗", text: "Climb a 14er", theme: "advent" },
  { emoji: "🏜️", text: "Hike the Appalachian Trail", theme: "advent" },
  { emoji: "🏔️", text: "Summit Mount Rainier", theme: "advent" },
  { emoji: "🌋", text: "Visit every national park", theme: "advent" },
  { emoji: "🛤️", text: "Bike across the country", theme: "advent" },
  { emoji: "🏁", text: "Race in a triathlon", theme: "run" },
  { emoji: "🦈", text: "Swim with sharks", theme: "water" },
  { emoji: "🐋", text: "Go whale watching", theme: "water" },
  { emoji: "🐎", text: "Learn polo", theme: "animal" },
  { emoji: "🎳", text: "Join a bowling league", theme: "game" },
  { emoji: "⛳", text: "Break 80 in golf", theme: "game" },
  { emoji: "🏓", text: "Get competitive at ping pong", theme: "game" },
  { emoji: "🥋", text: "Earn a black belt", theme: "combat" },
  { emoji: "🤼", text: "Learn wrestling", theme: "combat" },
  { emoji: "🏌️", text: "Master disc golf", theme: "game" },
  { emoji: "🎾", text: "Win a tennis tournament", theme: "game" },
  { emoji: "🧘", text: "Complete a silent retreat", theme: "zen" },
  { emoji: "📿", text: "Start a meditation practice", theme: "zen" },
  { emoji: "🖋️", text: "Learn hand lettering", theme: "art" },
  { emoji: "🎞️", text: "Make a short film", theme: "write" },
  { emoji: "🎙️", text: "Produce a documentary", theme: "write" },
  { emoji: "📺", text: "Start a Twitch stream", theme: "write" },
  { emoji: "🖌️", text: "Learn oil painting", theme: "art" },
  { emoji: "✏️", text: "Learn to draw portraits", theme: "art" },
  { emoji: "🗿", text: "Learn stone carving", theme: "art" },
  { emoji: "🪆", text: "Learn wood turning", theme: "art" },
  { emoji: "🧱", text: "Build a brick oven", theme: "build" },
  { emoji: "🔩", text: "Restore vintage tools", theme: "build" },
  { emoji: "🏚️", text: "Flip a house", theme: "build" },
  { emoji: "🪑", text: "Build custom furniture", theme: "build" },
  { emoji: "🛋️", text: "Learn upholstery", theme: "build" },
  { emoji: "🔦", text: "Build a van conversion", theme: "build" },
  { emoji: "⚡", text: "Install solar panels at home", theme: "build" },
  { emoji: "🌱", text: "Start composting", theme: "garden" },
  { emoji: "🐛", text: "Start a worm farm", theme: "garden" },
  { emoji: "🐟", text: "Build an aquaponics system", theme: "water" },
  { emoji: "🫚", text: "Grow medicinal herbs", theme: "garden" },
  { emoji: "🍇", text: "Make my own wine", theme: "drink" },
  { emoji: "🍎", text: "Start an orchard", theme: "farm" },
  { emoji: "🥕", text: "Run a CSA farm share", theme: "farm" },
  { emoji: "🐑", text: "Raise sheep", theme: "farm" },
  { emoji: "🐐", text: "Start a goat dairy", theme: "farm" },
  { emoji: "🧈", text: "Learn to make butter", theme: "farm" },
  { emoji: "🍯", text: "Harvest my own honey", theme: "farm" },
  { emoji: "🥧", text: "Win a pie baking contest", theme: "bake" },
  { emoji: "🍰", text: "Master cake decorating", theme: "bake" },
  { emoji: "🧆", text: "Master Middle Eastern cooking", theme: "cook" },
  { emoji: "🌮", text: "Master Mexican cooking", theme: "cook" },
  { emoji: "🥘", text: "Master Ethiopian cooking", theme: "cook" },
  { emoji: "🍲", text: "Master Korean cooking", theme: "cook" },
  { emoji: "🫕", text: "Master fondue", theme: "cook" },
  { emoji: "🥩", text: "Dry-age my own steaks", theme: "cook" },
  { emoji: "🐙", text: "Cook every Julia Child recipe", theme: "cook" },];
