"use client";

import { useState, useEffect } from "react";

export function SafetyPrivacyFooter() {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (open) {
      document.body.style.overflow = "hidden";
      return () => {
        document.body.style.overflow = "";
      };
    }
  }, [open]);

  return (
    <>
      <footer className="flex items-center justify-between px-4 py-2">
        <a
          href="https://x.com/mk_wlsn"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[11px] sm:text-[13px] text-zinc-400 hover:text-zinc-500 dark:text-zinc-700 dark:hover:text-zinc-400 transition-colors"
        >
          @mk_wlsn
        </a>
        <button
          onClick={() => setOpen(true)}
          className="text-[11px] sm:text-[13px] text-zinc-400 hover:text-zinc-500 dark:text-zinc-700 dark:hover:text-zinc-400 transition-colors"
        >
          Safety & privacy
        </button>
      </footer>

      {open && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4"
          onClick={() => setOpen(false)}
        >
          <div className="fixed inset-0 bg-black/50 backdrop-blur-sm" />
          <div
            className="relative w-full max-w-md rounded-xl bg-white p-6 shadow-2xl dark:bg-zinc-900"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              onClick={() => setOpen(false)}
              className="absolute right-4 top-4 text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-300 transition-colors"
              aria-label="Close"
            >
              <svg
                width="16"
                height="16"
                viewBox="0 0 16 16"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
              >
                <path d="M4 4l8 8M12 4l-8 8" />
              </svg>
            </button>

            <h2 className="text-lg font-semibold text-zinc-900 dark:text-zinc-100 mb-4">
              Safety & privacy
            </h2>

            <div className="space-y-4 text-sm text-zinc-600 dark:text-zinc-400">
              <div>
                <h3 className="font-medium text-zinc-800 dark:text-zinc-200 mb-1">
                  AI-generated content
                </h3>
                <p>
                  This is an AI-powered experience. All roadmaps and suggestions
                  are generated by a language model and may contain inaccuracies,
                  outdated information, or unhelpful advice. Take everything with
                  a big grain of salt and use your own judgment.
                </p>
              </div>

              <div>
                <h3 className="font-medium text-zinc-800 dark:text-zinc-200 mb-1">
                  Analytics
                </h3>
                <p>
                  We use Vercel Analytics to improve this product. This includes
                  the prompts you submit and the thumbs-up / thumbs-down ratings
                  you give to generated roadmaps. This data helps us understand
                  what&apos;s working and what isn&apos;t so we can make the
                  experience better.
                </p>
              </div>
            </div>

            <button
              onClick={() => setOpen(false)}
              className="mt-6 w-full rounded-lg bg-zinc-900 py-2 text-sm font-medium text-white hover:bg-zinc-800 dark:bg-zinc-100 dark:text-zinc-900 dark:hover:bg-zinc-200 transition-colors"
            >
              Got it
            </button>
          </div>
        </div>
      )}
    </>
  );
}
